[package]
name = "back"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.9.0"
derive = "1.0.0"
dotenvy = "0.15.7"
features = "0.10.0"
serde = { version = "1.0.214", features = ["derive"] }
