services:
  front:
    container_name: spacerework-back-container
    build:
      context: . # Chemin du répertoire où se trouve le Dockerfile
      dockerfile: Dockerfile
    image: spacerework-back-image
    ports:
      - "8080:8080"
    volumes:
      # Les volumes sont montés lors du démarrage du conteneur
      # mais avant les commandes CMD / ENTRYPOINT
      - ./src:/app/src
      - ./tests:/app/tests
    tty: true